import AppKit

/// Watches the general pasteboard and hands every new copy to the shelf when
/// the user has enabled clipboard watching. Polling changeCount is the only
/// way to observe the pasteboard on macOS; it is what every clipboard manager
/// does.
final class ClipboardMonitor {
    static let defaultsKey = "WatchClipboard"

    static var isEnabled: Bool {
        get { UserDefaults.standard.bool(forKey: defaultsKey) }
        set { UserDefaults.standard.set(newValue, forKey: defaultsKey) }
    }

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let onCapture: (NSPasteboard) -> Void

    /// Types password managers and similar apps use to mark clipboard data
    /// that must not be captured.
    private static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    init(onCapture: @escaping (NSPasteboard) -> Void) {
        self.onCapture = onCapture
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.tick()
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard Self.isEnabled else { return }
        guard !isSensitive() else { return }
        onCapture(pasteboard)
    }

    private func isSensitive() -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { Self.sensitiveTypes.contains($0.rawValue) }
    }
}
